# -*- coding: utf-8 -*-
"""BankNote

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zd56pt8mPYe1Kg2cnnePmxaymVeBXTnc
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import pickle

df=pd.read_csv('BankNote_Authentication.csv')

X=df.iloc[:,:-1]
y=df.iloc[:,-1]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,stratify=y)

dt_clf=DecisionTreeClassifier()
dt_clf.fit(X_train,y_train)

y_pred_train1=dt_clf.predict(X_train)
y_pred1=dt_clf.predict(X_test)

from sklearn.metrics import accuracy_score
test_score=accuracy_score(y_test,y_pred1)
train_score=accuracy_score(y_train,y_pred_train1)

train_score

test_score

pickle_out = open("BankNote.pickle","wb")
pickle.dump(dt_clf, pickle_out)
pickle_out.close()